# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HelloWorld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HelloWorld.proto',
  package='hello_world',
  syntax='proto3',
  serialized_pb=_b('\n\x10HelloWorld.proto\x12\x0bhello_world\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x10GreetingResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t2W\n\x0fGreetingService\x12\x44\n\x05Greet\x12\x1c.hello_world.GreetingRequest\x1a\x1d.hello_world.GreetingResponseB4\n\x1f\x63om.github.adilevin.hello_worldB\x0fHelloWorldProtoP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GREETINGREQUEST = _descriptor.Descriptor(
  name='GreetingRequest',
  full_name='hello_world.GreetingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello_world.GreetingRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=64,
)


_GREETINGRESPONSE = _descriptor.Descriptor(
  name='GreetingResponse',
  full_name='hello_world.GreetingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_text', full_name='hello_world.GreetingResponse.response_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['GreetingRequest'] = _GREETINGREQUEST
DESCRIPTOR.message_types_by_name['GreetingResponse'] = _GREETINGRESPONSE

GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GREETINGREQUEST,
  __module__ = 'HelloWorld_pb2'
  # @@protoc_insertion_point(class_scope:hello_world.GreetingRequest)
  ))
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GREETINGRESPONSE,
  __module__ = 'HelloWorld_pb2'
  # @@protoc_insertion_point(class_scope:hello_world.GreetingResponse)
  ))
_sym_db.RegisterMessage(GreetingResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037com.github.adilevin.hello_worldB\017HelloWorldProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class GreetingServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Greet = channel.unary_unary(
          '/hello_world.GreetingService/Greet',
          request_serializer=GreetingRequest.SerializeToString,
          response_deserializer=GreetingResponse.FromString,
          )


  class GreetingServiceServicer(object):

    def Greet(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_GreetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Greet': grpc.unary_unary_rpc_method_handler(
            servicer.Greet,
            request_deserializer=GreetingRequest.FromString,
            response_serializer=GreetingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'hello_world.GreetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaGreetingServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Greet(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaGreetingServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Greet(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Greet.future = None


  def beta_create_GreetingService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('hello_world.GreetingService', 'Greet'): GreetingRequest.FromString,
    }
    response_serializers = {
      ('hello_world.GreetingService', 'Greet'): GreetingResponse.SerializeToString,
    }
    method_implementations = {
      ('hello_world.GreetingService', 'Greet'): face_utilities.unary_unary_inline(servicer.Greet),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_GreetingService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('hello_world.GreetingService', 'Greet'): GreetingRequest.SerializeToString,
    }
    response_deserializers = {
      ('hello_world.GreetingService', 'Greet'): GreetingResponse.FromString,
    }
    cardinalities = {
      'Greet': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'hello_world.GreetingService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
